apiVersion: apps/v1
kind: Deployment
metadata:
  name: impulsio-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impulsio-web
  template:
    metadata:
      labels:
        app: impulsio-web
    spec:
      containers:
      - name: web
        image: dodge100/impulsio-web:1.0
        ports:
        - containerPort: 80
